language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install -r requirements-dev.txt --use-wheel"
  - "python setup.py install"
script:
  - "flake8 seed_services_cli"
  - "py.test seed_services_cli"
